"""
Fuzzy Rule Base for IntelliIncident Soft Computing Risk Assessment
Defines Mamdani IF-THEN rules for incident risk evaluation.
"""

from typing import List, Dict, Any

FUZZY_RULES = [
    {
        "id": "RULE-01",
        "antecedents": {"error_rate": "HIGH", "user_impact": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Error Rate is HIGH AND User Impact is HIGH THEN Risk is VERY HIGH",
        "description": "Catastrophic business failure pattern with broad customer-facing errors.",
        "contribution": "High activation from concurrent error rate and broad user impact.",
    },
    {
        "id": "RULE-02",
        "antecedents": {"latency": "HIGH", "service_criticality": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Latency is HIGH AND Service Criticality is HIGH THEN Risk is HIGH",
        "description": "Tier-1 SLA breach due to severe responsiveness degradation.",
        "contribution": "Elevated latency on mission-critical service.",
    },
    {
        "id": "RULE-03",
        "antecedents": {"deployment_recency": "RECENT", "error_rate": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Deployment Recency is RECENT AND Error Rate is HIGH THEN Risk is VERY HIGH",
        "description": "Defective deployment anomaly with immediate regression impact.",
        "contribution": "Temporal proximity to recent release correlates strongly with failure.",
    },
    {
        "id": "RULE-04",
        "antecedents": {"error_rate": "MEDIUM", "user_impact": "MEDIUM"},
        "consequent": "MEDIUM",
        "ruleText": "IF Error Rate is MEDIUM AND User Impact is MEDIUM THEN Risk is MEDIUM",
        "description": "Moderate operational incident with contained blast radius.",
        "contribution": "Moderate operating telemetry within acceptable variance.",
    },
    {
        "id": "RULE-05",
        "antecedents": {"latency": "MEDIUM", "service_criticality": "LOW"},
        "consequent": "LOW",
        "ruleText": "IF Latency is MEDIUM AND Service Criticality is LOW THEN Risk is LOW",
        "description": "Background or non-critical latency elevation within tolerable limits.",
        "contribution": "Low criticality tier dampens latency impact.",
    },
    {
        "id": "RULE-06",
        "antecedents": {"error_rate": "LOW", "user_impact": "LOW"},
        "consequent": "LOW",
        "ruleText": "IF Error Rate is LOW AND User Impact is LOW THEN Risk is LOW",
        "description": "Nominal baseline operational state.",
        "contribution": "Nominal operational telemetry baseline.",
    },
    {
        "id": "RULE-07",
        "antecedents": {"deployment_recency": "RECENT", "latency": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Deployment Recency is RECENT AND Latency is HIGH THEN Risk is HIGH",
        "description": "Post-release performance degradation or resource contention.",
        "contribution": "Recent code deployment causing latency degradation.",
    },
    {
        "id": "RULE-08",
        "antecedents": {"service_criticality": "HIGH", "user_impact": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Service Criticality is HIGH AND User Impact is HIGH THEN Risk is VERY HIGH",
        "description": "Severe consumer disruption on critical tier service.",
        "contribution": "High customer blast radius on Tier 1 infrastructure.",
    },
    {
        "id": "RULE-09",
        "antecedents": {"error_rate": "HIGH", "latency": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Error Rate is HIGH AND Latency is HIGH THEN Risk is VERY HIGH",
        "description": "Cascading service failure across both reliability and speed.",
        "contribution": "Dual degradation across latency and reliability metrics.",
    },
    {
        "id": "RULE-10",
        "antecedents": {"error_rate": "LOW", "latency": "LOW", "service_criticality": "LOW"},
        "consequent": "LOW",
        "ruleText": "IF Error Rate is LOW AND Latency is LOW AND Service Criticality is LOW THEN Risk is LOW",
        "description": "Healthy non-critical operations.",
        "contribution": "Clean telemetry on auxiliary service.",
    },
    {
        "id": "RULE-11",
        "antecedents": {"error_rate": "HIGH", "service_criticality": "MEDIUM"},
        "consequent": "HIGH",
        "ruleText": "IF Error Rate is HIGH AND Service Criticality is MEDIUM THEN Risk is HIGH",
        "description": "Elevated failure rate on standard tier production services.",
        "contribution": "High error frequency across core operational workload.",
    },
    {
        "id": "RULE-12",
        "antecedents": {"error_rate": "HIGH", "service_criticality": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Error Rate is HIGH AND Service Criticality is HIGH THEN Risk is VERY HIGH",
        "description": "Mission-critical service suffering elevated error spikes.",
        "contribution": "Direct threat to Tier-1 infrastructure uptime.",
    },
    {
        "id": "RULE-13",
        "antecedents": {"error_rate": "HIGH", "user_impact": "LOW"},
        "consequent": "MEDIUM",
        "ruleText": "IF Error Rate is HIGH AND User Impact is LOW THEN Risk is MEDIUM",
        "description": "High error rate contained to isolated or low-volume consumers.",
        "contribution": "Severe errors but with limited customer blast radius.",
    },
    {
        "id": "RULE-14",
        "antecedents": {"error_rate": "MEDIUM", "user_impact": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Error Rate is MEDIUM AND User Impact is HIGH THEN Risk is HIGH",
        "description": "Broad customer exposure to moderate error rates.",
        "contribution": "Wide blast radius amplifies moderate failure frequency.",
    },
    {
        "id": "RULE-15",
        "antecedents": {"error_rate": "MEDIUM", "service_criticality": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Error Rate is MEDIUM AND Service Criticality is HIGH THEN Risk is HIGH",
        "description": "Moderate degradation on mission-critical infrastructure.",
        "contribution": "High service tier escalates moderate errors.",
    },
    {
        "id": "RULE-16",
        "antecedents": {"latency": "HIGH", "user_impact": "HIGH"},
        "consequent": "VERY_HIGH",
        "ruleText": "IF Latency is HIGH AND User Impact is HIGH THEN Risk is VERY HIGH",
        "description": "Massive latency impact affecting large user cohort.",
        "contribution": "Extensive user exposure to severe performance delays.",
    },
    {
        "id": "RULE-17",
        "antecedents": {"latency": "HIGH", "user_impact": "MEDIUM"},
        "consequent": "HIGH",
        "ruleText": "IF Latency is HIGH AND User Impact is MEDIUM THEN Risk is HIGH",
        "description": "Significant latency degradation with moderate audience impact.",
        "contribution": "Noticeable performance bottleneck affecting active sessions.",
    },
    {
        "id": "RULE-18",
        "antecedents": {"deployment_recency": "RECENT", "service_criticality": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Deployment Recency is RECENT AND Service Criticality is HIGH THEN Risk is HIGH",
        "description": "Recent release deployment on mission-critical system elevates operational exposure.",
        "contribution": "Heightened operational risk during recent release rollout on Tier-1 infrastructure.",
    },
    {
        "id": "RULE-19",
        "antecedents": {"error_rate": "MEDIUM", "latency": "HIGH"},
        "consequent": "HIGH",
        "ruleText": "IF Error Rate is MEDIUM AND Latency is HIGH THEN Risk is HIGH",
        "description": "Combined latency and error degradation.",
        "contribution": "Correlated response degradation and failure rates.",
    },
    {
        "id": "RULE-20",
        "antecedents": {"error_rate": "LOW", "user_impact": "HIGH"},
        "consequent": "MEDIUM",
        "ruleText": "IF Error Rate is LOW AND User Impact is HIGH THEN Risk is MEDIUM",
        "description": "Large active user base operating under nominal error rates.",
        "contribution": "Large blast radius requires heightened operational awareness.",
    },
    {
        "id": "RULE-21",
        "antecedents": {"error_rate": "LOW", "service_criticality": "HIGH"},
        "consequent": "MEDIUM",
        "ruleText": "IF Error Rate is LOW AND Service Criticality is HIGH THEN Risk is MEDIUM",
        "description": "Nominal telemetry on mission-critical service.",
        "contribution": "Mission-critical baseline stability.",
    },
    {
        "id": "RULE-22",
        "antecedents": {"latency": "MEDIUM", "service_criticality": "HIGH"},
        "consequent": "MEDIUM",
        "ruleText": "IF Latency is MEDIUM AND Service Criticality is HIGH THEN Risk is MEDIUM",
        "description": "Moderate latency on mission-critical service.",
        "contribution": "Minor latency elevation on critical path.",
    },
    {
        "id": "RULE-23",
        "antecedents": {"deployment_recency": "RECENT", "error_rate": "MEDIUM"},
        "consequent": "MEDIUM",
        "ruleText": "IF Deployment Recency is RECENT AND Error Rate is MEDIUM THEN Risk is MEDIUM",
        "description": "Moderate error rate following recent release.",
        "contribution": "Potential minor regression introduced by deployment.",
    },
    {
        "id": "RULE-24",
        "antecedents": {"error_rate": "MEDIUM", "user_impact": "LOW"},
        "consequent": "LOW",
        "ruleText": "IF Error Rate is MEDIUM AND User Impact is LOW THEN Risk is LOW",
        "description": "Contained moderate error rate with minimal user impact.",
        "contribution": "Low blast radius keeps risk low.",
    },
    {
        "id": "RULE-25",
        "antecedents": {"error_rate": "LOW", "user_impact": "MEDIUM"},
        "consequent": "MEDIUM",
        "ruleText": "IF Error Rate is LOW AND User Impact is MEDIUM THEN Risk is MEDIUM",
        "description": "Moderate user audience encountering baseline low errors.",
        "contribution": "Moderate audience exposure under nominal performance.",
    },
    {
        "id": "RULE-26",
        "antecedents": {"latency": "MEDIUM", "service_criticality": "MEDIUM"},
        "consequent": "MEDIUM",
        "ruleText": "IF Latency is MEDIUM AND Service Criticality is MEDIUM THEN Risk is MEDIUM",
        "description": "Moderate latency on standard tier service.",
        "contribution": "Acceptable variance on standard operational tier.",
    },
    {
        "id": "RULE-27",
        "antecedents": {"deployment_recency": "RECENT", "user_impact": "MEDIUM"},
        "consequent": "MEDIUM",
        "ruleText": "IF Deployment Recency is RECENT AND User Impact is MEDIUM THEN Risk is MEDIUM",
        "description": "Recent release affecting moderate user audience.",
        "contribution": "Post-release telemetry monitoring with moderate user exposure.",
    },
    {
        "id": "RULE-28",
        "antecedents": {"error_rate": "HIGH", "user_impact": "MEDIUM"},
        "consequent": "HIGH",
        "ruleText": "IF Error Rate is HIGH AND User Impact is MEDIUM THEN Risk is HIGH",
        "description": "Elevated failure rate with moderate customer exposure.",
        "contribution": "High error frequency across active customer sessions.",
    },
]
